server_grpc:
  #host: host.docker.internal
  host: localhost
  port: 50051

server_rest:
  #host: http://host.docker.internal
  host: localhost
  port: 8000

influxdb:
  #host: influxdb
  host: localhost
  port: 8086